[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "debug"

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip RP2040 --probe 2e8a:000c"
# rustflags = [
#   "-C", "link-arg=--nmagic",
# ]

[alias]
fw-build = "build --no-default-features --features mock-bus,defmt-log"
fw-run = "run --no-default-features --features mock-bus,defmt-log"
fw-build-passive = "build --no-default-features --features pio-passive,defmt-log"
fw-run-passive = "run --no-default-features --features pio-passive,defmt-log"
fw-build-master = "build --no-default-features --features pio-master,defmt-log"
fw-run-master = "run --no-default-features --features pio-master,defmt-log"
